name: Continuous Integration

on:
  pull_request

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Using node.js
        uses: actions/setup-node@v4
        with:
          node_version: 20.
      - name: run install, build and test
        run: |
          npm install
          npm run build
          npm run test